"""
Django settings for gce_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse, parse_qs
try:
    from dotenv import load_dotenv
except Exception:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment from .env file if present (local dev convenience)
# Allow disabling .env autoload for utility subprocesses
if load_dotenv is not None and not os.environ.get('DJANGO_SKIP_DOTENV'):
    load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ahpth=)kw*yhirtcd-9+(%+rf)e^ks_p2wwxxp0^sm+gkh$=i+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gce_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Project-level template overrides (for admin custom nav, etc.)
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gce_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _database_from_env():
    """Build DATABASES['default'] from environment variables.

    Priority:
      1) DATABASE_URL if provided and starts with postgres/postgresql
      2) DB_ENGINE=postgres + discrete vars (DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT)
      3) Fallback to local SQLite (development default)
    """

    db_url = os.environ.get('DATABASE_URL', '').strip()
    db_engine_env = os.environ.get('DB_ENGINE', '').strip().lower()

    # PostgreSQL via URL
    if db_url and db_url.lower().startswith(('postgres://', 'postgresql://')):
        u = urlparse(db_url)
        name = (u.path or '').lstrip('/') or os.environ.get('DB_NAME', '')
        default_port = '5432'
        query = parse_qs(u.query)
        options = {}
        # Optional sslmode from query string
        sslm = query.get('sslmode', [None])[0]
        if sslm:
            options['sslmode'] = sslm
        connect_timeout = os.environ.get('DB_CONNECT_TIMEOUT')
        if connect_timeout:
            try:
                options['connect_timeout'] = int(connect_timeout)
            except Exception:
                pass

        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': name,
            'USER': u.username or os.environ.get('DB_USER', ''),
            'PASSWORD': u.password or os.environ.get('DB_PASSWORD', ''),
            'HOST': u.hostname or os.environ.get('DB_HOST', 'localhost'),
            'PORT': str(u.port or os.environ.get('DB_PORT', default_port)),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
            'OPTIONS': options,
        }

    # PostgreSQL via discrete env vars
    if db_engine_env in ('postgres', 'postgresql', 'pg', 'psql'):
        options = {}
        sslmode = os.environ.get('DB_SSLMODE')
        if sslmode:
            options['sslmode'] = sslmode
        connect_timeout = os.environ.get('DB_CONNECT_TIMEOUT')
        if connect_timeout:
            try:
                options['connect_timeout'] = int(connect_timeout)
            except Exception:
                pass
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'gce3'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
            'OPTIONS': options,
        }

    # Default: SQLite (dev)
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,
        },
    }


DATABASES = {
    'default': _database_from_env()
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Server default timezone (display, conversions)
TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# TradeStation CSV exports directory
TS_EXPORTS_DIR = os.environ.get('TS_EXPORTS_DIR', r'C:\\TS_EXPORTS')

# Background services autostart
AUTOSTART_INGESTION = False  # legacy ingestion disabled in global-feed mode
AUTOSTART_MT5_MONITORING = True
AUTOSTART_GLOBAL_INGESTION = True
DUAL_WRITE_GLOBAL_FEED = True
LEGACY_WRITE_ENABLED = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
