# Generated by Django 5.2.6 on 2025-09-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MT5ConnectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название для этого набора настроек', max_length=100, unique=True, verbose_name='Название настройки')),
                ('terminal_path', models.CharField(blank=True, help_text='Полный путь к исполняемому файлу terminal64.exe', max_length=500, null=True, verbose_name='Путь к терминалу MT5')),
                ('server', models.CharField(blank=True, help_text='Название торгового сервера (например: MetaQuotes-Demo)', max_length=100, verbose_name='Сервер')),
                ('login', models.BigIntegerField(blank=True, help_text='Номер торгового счета', null=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, help_text='Пароль торгового счета', max_length=100, verbose_name='Пароль')),
                ('timeout', models.IntegerField(default=60000, help_text='Таймаут подключения в миллисекундах', verbose_name='Таймаут (мс)')),
                ('portable', models.BooleanField(default=False, help_text='Запуск терминала в портативном режиме', verbose_name='Портативный режим')),
                ('is_active', models.BooleanField(default=True, help_text='Использовать эти настройки для подключения', verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать как настройки по умолчанию', verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о настройках', verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Настройки MT5',
                'verbose_name_plural': 'Настройки MT5',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MT5ConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_time', models.DateTimeField(auto_now_add=True, verbose_name='Время подключения')),
                ('success', models.BooleanField(verbose_name='Успешно')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('account_info', models.JSONField(blank=True, null=True, verbose_name='Информация о счете')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mt5connectionsettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Лог подключения MT5',
                'verbose_name_plural': 'Логи подключений MT5',
                'ordering': ['-connection_time'],
            },
        ),
    ]
