# Generated by Django 5.2.6 on 2025-09-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5connectionsettings',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Текущий баланс счета', max_digits=15, null=True, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='mt5connectionsettings',
            name='equity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Текущее эквити счета', max_digits=15, null=True, verbose_name='Эквити'),
        ),
        migrations.AddField(
            model_name='mt5connectionsettings',
            name='last_connection_time',
            field=models.DateTimeField(blank=True, help_text='Время последнего успешного подключения', null=True, verbose_name='Последнее подключение'),
        ),
    ]
