# Generated by Django 5.2.4 on 2025-09-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mt5connectionsettings_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5MonitoringSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_check_interval', models.IntegerField(default=30, help_text='How often to check connection health', verbose_name='Health Check Interval (seconds)')),
                ('reconnect_interval', models.IntegerField(default=60, help_text='How often to attempt reconnection when disconnected', verbose_name='Reconnect Interval (seconds)')),
                ('max_reconnect_attempts', models.IntegerField(default=5, help_text='Maximum number of consecutive reconnection attempts', verbose_name='Max Reconnect Attempts')),
                ('enable_email_alerts', models.BooleanField(default=False, verbose_name='Enable Email Alerts')),
                ('alert_email', models.EmailField(blank=True, max_length=254, verbose_name='Alert Email Address')),
                ('health_records_retention_days', models.IntegerField(default=30, help_text='How long to keep health check records', verbose_name='Health Records Retention (days)')),
                ('monitoring_enabled', models.BooleanField(default=True, help_text='Enable/disable the entire monitoring system', verbose_name='Enable Monitoring')),
                ('auto_reconnect_enabled', models.BooleanField(default=True, help_text='Automatically attempt to reconnect when connection is lost', verbose_name='Enable Auto-Reconnect')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'MT5 Monitoring Settings',
                'verbose_name_plural': 'MT5 Monitoring Settings',
            },
        ),
        migrations.CreateModel(
            name='MT5ConnectionHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='Check Time')),
                ('is_connected', models.BooleanField(verbose_name='Is Connected')),
                ('ping_ms', models.IntegerField(blank=True, help_text='Connection response time in milliseconds', null=True, verbose_name='Ping (ms)')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Account Balance')),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Account Equity')),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Used Margin')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='main.mt5connectionsettings', verbose_name='Connection Settings')),
            ],
            options={
                'verbose_name': 'MT5 Connection Health Record',
                'verbose_name_plural': 'MT5 Connection Health Records',
                'ordering': ['-check_time'],
                'indexes': [models.Index(fields=['settings', '-check_time'], name='main_mt5con_setting_1b02c3_idx'), models.Index(fields=['is_connected', '-check_time'], name='main_mt5con_is_conn_52a33b_idx')],
            },
        ),
    ]
