# Generated by Django 5.2.6 on 2025-10-01 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mt5monitoringsettings_mt5connectionhealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_sid', models.CharField(help_text='Краткое название системы (например: DOTBIN, TestSys)', max_length=50, unique=True, verbose_name='System ID')),
                ('name', models.CharField(help_text='Полное описательное название торговой системы', max_length=200, verbose_name='Название системы')),
                ('symbol', models.CharField(default='EURUSD', help_text='Торговая пара (например: EURUSD, GBPUSD)', max_length=20, verbose_name='Валютная пара')),
                ('timeframes_count', models.PositiveIntegerField(default=1, help_text='Сколько разных таймфреймов использует система', verbose_name='Количество таймфреймов')),
                ('time_offset_minutes', models.IntegerField(default=0, help_text='Сдвиг времени в минутах (может быть отрицательным)', verbose_name='Сдвиг времени (минуты)')),
                ('is_active', models.BooleanField(default=True, help_text='Обрабатывать ли данные этой системы', verbose_name='Активна')),
                ('description', models.TextField(blank=True, help_text='Подробное описание торговой системы', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Торговая система',
                'verbose_name_plural': 'Торговые системы',
                'ordering': ['system_sid'],
            },
        ),
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('M1', '1 Minute'), ('M2', '2 Minutes'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('M30', '30 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '1 Day'), ('W1', '1 Week'), ('MN1', '1 Month')], max_length=10, verbose_name='Таймфрейм')),
                ('level', models.PositiveIntegerField(help_text='Уровень важности таймфрейма (1 - самый важный)', verbose_name='Уровень')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('trading_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeframes', to='main.tradingsystem', verbose_name='Торговая система')),
            ],
            options={
                'verbose_name': 'Таймфрейм',
                'verbose_name_plural': 'Таймфреймы',
                'ordering': ['trading_system', 'level'],
                'unique_together': {('trading_system', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('file_modified', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения файла')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Обработан'), ('error', 'Ошибка'), ('skipped', 'Пропущен')], default='pending', max_length=20, verbose_name='Статус')),
                ('rows_processed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Обработано строк')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('json_data', models.JSONField(blank=True, help_text='Преобразованные данные в JSON формате', null=True, verbose_name='JSON данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('timeframe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='main.timeframe', verbose_name='Таймфрейм')),
                ('trading_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='main.tradingsystem', verbose_name='Торговая система')),
            ],
            options={
                'verbose_name': 'Файл данных',
                'verbose_name_plural': 'Файлы данных',
                'ordering': ['-file_modified', 'filename'],
                'unique_together': {('trading_system', 'filename')},
            },
        ),
    ]
