# Generated by Django 5.2.4 on 2025-10-01 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_dataingestionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('imported', 'Imported'), ('no_change', 'No Change'), ('error', 'Error')], max_length=20)),
                ('rows_imported', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        migrations.AddField(
            model_name='importlog',
            name='data_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.datafile'),
        migrations.AddField(
            model_name='importlog',
            name='timeframe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.timeframe'),
        migrations.AddField(
            model_name='importlog',
            name='trading_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tradingsystem'),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['-created_at'], name='main_import_created_2afcd5_idx'),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['action', '-created_at'], name='main_import_action_53ac73_idx'),
    ]


