# Generated by Django 5.2.6 on 2025-10-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_importlog'),
    ]

    operations = []
