# Generated by Django 5.2.6 on 2025-10-02 18:00

from django.db import migrations, models


def _noop(apps, schema_editor):
    # This migration was auto-generated to rename indexes, but on some
    # environments the old index names do not exist (already renamed or created
    # with new names). Make it a no-op to keep migration sequence consistent.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_signalevent_action'),
    ]

    operations = [
        migrations.RunPython(_noop, migrations.RunPython.noop),
    ]
