# Generated by Django 5.2.6 on 2025-10-02 18:10

from django.db import migrations, models


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_tradingsystem_trading_controls'),
    ]

    operations = [
        migrations.RunPython(_noop, migrations.RunPython.noop),
    ]
