# Generated by Django 5.2.6 on 2025-10-02 18:22

from django.db import migrations, models


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_signalexecutionlog'),
    ]

    operations = [
        migrations.RunPython(_noop, migrations.RunPython.noop),
    ]
