# Generated by Django 5.2.6 on 2025-10-02 18:25

from django.db import migrations, models


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_main_bar_timefra_1a1df7_idx_main_bar_timefra_c20326_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(_noop, migrations.RunPython.noop),
    ]
