# Generated by Django 5.2.6 on 2025-10-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_marketbar_created_at'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL('DROP INDEX IF EXISTS "main_signal_system__7b2c63_idx";', reverse_sql=''),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='signalevent',
                    name='main_signal_system__7b2c63_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL('DROP INDEX IF EXISTS "main_signal_bar_direc_3d9265_idx";', reverse_sql=''),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='signalevent',
                    name='main_signal_bar_direc_3d9265_idx',
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name='datafeed',
            new_name='main_datafe_provide_f41ce9_idx',
            old_name='main_datafe_provide_9d2464_idx',
        ),
        migrations.RenameIndex(
            model_name='datafeed',
            new_name='main_datafe_instrum_e8ac41_idx',
            old_name='main_datafe_instrum_0a7f7d_idx',
        ),
        migrations.RenameIndex(
            model_name='marketbar',
            new_name='main_market_feed_id_5ac748_idx',
            old_name='main_market_feed_id_b6c67e_idx',
        ),
        migrations.RenameIndex(
            model_name='marketbar',
            new_name='main_market_dt_641286_idx',
            old_name='main_market__dt_c2dc2f_idx',
        ),
        migrations.RenameIndex(
            model_name='marketdatafile',
            new_name='main_market_provide_d4b613_idx',
            old_name='main_market_provide_919060_idx',
        ),
        migrations.RenameIndex(
            model_name='marketdatafile',
            new_name='main_market_feed_id_abe195_idx',
            old_name='main_market_feed_id_b62b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='marketindicatordef',
            new_name='main_market_feed_id_c252f6_idx',
            old_name='main_market_feed_id_d1ffd2_idx',
        ),
        migrations.RenameIndex(
            model_name='marketindicatorvalue',
            new_name='main_market_indicat_f2eeaa_idx',
            old_name='main_market_indicat_855ac8_idx',
        ),
        migrations.RenameIndex(
            model_name='signalevent',
            new_name='main_signal_trading_64a929_idx',
            old_name='main_signal_trading_1fbab6_idx',
        ),
        migrations.RenameIndex(
            model_name='signalevent',
            new_name='main_signal_feed_id_5d83c8_idx',
            old_name='main_signal_feed_id_44f9a9_idx',
        ),
        migrations.RenameIndex(
            model_name='signalevent',
            new_name='main_signal_directi_d7e2fe_idx',
            old_name='main_signal_dir_act_time_idx',
        ),
        migrations.RenameIndex(
            model_name='signalexecutionlog',
            new_name='main_signal_execute_e8155e_idx',
            old_name='main_signalexec_time_idx',
        ),
        migrations.RenameIndex(
            model_name='tradingsystemtfbinding',
            new_name='main_tradin_trading_4a1079_idx',
            old_name='main_tradin_trading_9a39c2_idx',
        ),
        migrations.AlterField(
            model_name='tradingsystem',
            name='symbol',
            field=models.CharField(default='EURUSD', max_length=20),
        ),
    ]
