# Generated by Django 5.2.6 on 2025-10-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_marketindicatordef_name_len'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketimporterror',
            new_name='main_market_data_fi_87f0d4_idx',
            old_name='main_mierr_file_created_idx',
        ),
        migrations.RenameIndex(
            model_name='marketimporterror',
            new_name='main_market_created_14a5f3_idx',
            old_name='main_mierr_created_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='signalevent',
            new_name='main_signal_trading_74fcc0_idx',
            old_name='main_signalevent_cycle_idx',
        ),
    ]
